[package]
name = "ordinance"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
csv = { workspace = true }
duckdb = { workspace = true }
thiserror = { workspace = true }
